### ISSUE TITLE
Autoscaling groups do not scale down

### ISSUE THREAD

**Issue by jjmcnelis** [mkarim2017/standard_product#13] opened 2021-07-19 17:18 UTC
**Describe the bug**
Auto Scaling groups do not scale down

This behavior has been observed with the Rise_Limonadi and Volcano_Lundgren ASGs over the last two weeks. (Those are the expensive ones.) Also the standard product enumerator ASG. 

**To Reproduce**
1. Go to the Auto Scaling Groups in the EC2 section of the AWS Management Console
2. Wait for all jobs to finish (viewing from RabbitMQ)
3. Note that the running instances do not terminate their instances on completion.

**Expected behavior**
Auto scaling groups do not terminate instances when the queues are complete/empty.

**Comment by riverma** [comment] 2021-07-19 17:31
Duplicate of https://github.com/aria-jpl/ops_scripts2/issues/2

**Closed as completed by riverma** 2021-07-19 17:31 UTC
